### PR TITLE
Feature/query multiple tables

### PR DESCRIPTION
**Pull request by Zafron047**
Dear Reviewer,
Please review the changes made and the queries implemented. Your feedback is greatly appreciated.

## **Project Requirements**

- Created owners table with columns id, full_name, and age.
- Created species table with columns id and name.
- Modified animals table to include species_id and owner_id columns.
- Inserted provided data into owners and species tables.
- Updated animals with appropriate species_id and owner_id.
- Implemented all changes in schema.sql and data.sql files.

## **Screenshots of Queries**
What animals belong to Melody Pond?

List of all animals that are pokemon (their type is Pokemon).

List all owners and their animals, including those without any animal.

How many animals are there per species?

List all Digimon owned by Jennifer Orwell.

List all animals owned by Dean Winchester that haven't tried to escape.

Who owns the most animals?

_**Notes**
- Implemented the specified database schema and data modifications.
- Ensured that queries produce accurate results according to requirements._

Thank you.

@Zafron047

### CODE REVIEW

**Review by Munsa1 — CHANGES_REQUESTED** [review]
Hi @Zafron047, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Added Screenshots For All Queries :heavy_check_mark: 
Correct Git Flow :heavy_check_mark: 
Descriptive ReadMe File :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._
### Due to insufficient files changed I will leave a comment here

- [x] Kindly fix the link to your Twitter profile as it is a broken link
image

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Zafron047** [comment]
@Munsa1 Fixed the broken link which had duplicate https in twitter url.

**Review by tufoinnkuo10 — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi @Zafron047 

Your project is complete! Great job 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- screenshots ok
- files well arranged

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Zafron047** [comment]
@tufoinnkuo10 Thanks for the review and approval.

**Pull request merged**
